version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-107-22-236-52.compute-1.amazonaws.com
            database: d8vouboijghrpj
            schema: management
            user: nqalllbzbccidb
            password: b43a831b59ebf870a1aaf9115a3138f0f3e1655ad9cbea900c8be04ed37f95ae
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true