version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-174-129-253-28.compute-1.amazonaws.com
            database: d4tqcru0dpuul9
            schema: management
            user: hsrjlwectbezdz
            password: 99b1728d7923df7c85d22e89ae3722626c87c91a6d7cfcb4c5282521b352a549
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true